import { StyleSheet } from 'react-native';
import { DesignColors, DesignRadius, DesignSpacing, DesignTypography, fontFamily } from '@/constants/design';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: DesignColors.surface },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.sm,
    paddingHorizontal: DesignSpacing.md,
    paddingVertical: DesignSpacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: DesignColors.borderFaint,
  },
  topBarTitle: {
    ...DesignTypography.headlineMd,
    color: DesignColors.onSurface,
    fontFamily,
    fontWeight: '700',
    fontSize: 17,
  },
  content: {
    padding: DesignSpacing.md,
    paddingBottom: DesignSpacing.xl,
    gap: DesignSpacing.lg,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: DesignSpacing.md,
    padding: DesignSpacing.lg,
  },
  footer: {
    padding: DesignSpacing.md,
    paddingTop: DesignSpacing.xs,
    gap: DesignSpacing.sm,
  },
  mutedText: {
    ...DesignTypography.bodyMd,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    lineHeight: 20,
    textAlign: 'center',
  },

  heroCard: {
    borderRadius: DesignRadius.xl,
    overflow: 'hidden',
    backgroundColor: DesignColors.glassSoft,
    borderWidth: 1,
    borderColor: DesignColors.glassBorder,
  },
  heroImage: { width: '100%', height: 120 },
  heroGradient: { ...StyleSheet.absoluteFillObject },
  heroFallback: {
    height: 80,
    backgroundColor: DesignColors.surfaceContainerHigh,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroInfo: { padding: DesignSpacing.md, gap: DesignSpacing.xs },
  heroLabel: {
    ...DesignTypography.labelSm,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    letterSpacing: 1.2,
  },
  heroTitle: {
    ...DesignTypography.bodyLg,
    color: DesignColors.onSurface,
    fontFamily,
    fontWeight: '700',
  },
  heroMeta: { flexDirection: 'row', gap: DesignSpacing.md },
  heroMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.xs,
  },
  heroMetaText: {
    ...DesignTypography.labelSm,
    color: DesignColors.primaryBright,
    fontFamily,
    fontWeight: '600',
  },

  amountCard: {
    backgroundColor: DesignColors.glassSoft,
    borderWidth: 1,
    borderColor: DesignColors.glassBorder,
    borderRadius: DesignRadius.xl,
    padding: DesignSpacing.lg,
    gap: DesignSpacing.xs,
  },
  amountHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.sm,
  },
  amountBar: {
    width: 3,
    height: 14,
    borderRadius: 2,
    backgroundColor: DesignColors.primaryBright,
  },
  amountLabel: {
    ...DesignTypography.labelCaps,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    letterSpacing: 1.4,
  },
  amountValue: {
    ...DesignTypography.headlineLg,
    color: DesignColors.primaryBright,
    fontFamily,
    fontWeight: '800',
    fontSize: 34,
  },
  amountDivider: {
    height: 1,
    backgroundColor: DesignColors.borderSoft,
    marginVertical: DesignSpacing.sm,
  },
  amountNote: {
    ...DesignTypography.bodyMd,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    lineHeight: 20,
  },

  payButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: DesignColors.primaryContainer,
    borderRadius: DesignRadius.full,
    paddingVertical: 16,
    shadowColor: DesignColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  payButtonDisabled: { opacity: 0.6 },
  payText: {
    ...DesignTypography.bodyLg,
    color: DesignColors.onPrimaryContainer,
    fontFamily,
    fontWeight: '700',
  },

  releaseLink: { alignItems: 'center', paddingVertical: DesignSpacing.xs },
  releaseText: {
    ...DesignTypography.bodyMd,
    color: DesignColors.error,
    fontFamily,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },

  glassCenterCard: {
    backgroundColor: DesignColors.glassSoft,
    borderRadius: DesignRadius.xl,
    borderWidth: 1,
    borderColor: DesignColors.glassBorder,
    padding: DesignSpacing.xl,
    alignItems: 'center',
    gap: DesignSpacing.md,
    width: '100%',
  },

  successBadge: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: DesignColors.secondary,
    borderWidth: 6,
    borderColor: DesignColors.primaryTintMid,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: DesignColors.secondary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  successTitle: {
    ...DesignTypography.headlineMd,
    color: DesignColors.onSurface,
    fontFamily,
    fontWeight: '800',
  },
  successAmount: {
    ...DesignTypography.headlineLg,
    color: DesignColors.secondary,
    fontFamily,
    fontWeight: '800',
  },
  successDivider: {
    width: 48,
    height: 3,
    borderRadius: 2,
    backgroundColor: DesignColors.primaryBright,
    marginVertical: DesignSpacing.xs,
  },

  errorBadge: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: DesignColors.errorContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  expiredTitle: {
    ...DesignTypography.headlineMd,
    color: DesignColors.error,
    fontFamily,
    fontWeight: '800',
  },
});
