import { StyleSheet } from 'react-native';
import { DesignColors, DesignRadius, DesignSpacing, DesignTypography, fontFamily } from '@/constants/design';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: DesignColors.surface },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.sm,
    paddingHorizontal: DesignSpacing.md,
    paddingVertical: DesignSpacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: DesignColors.borderFaint,
  },
  topBarTitle: {
    ...DesignTypography.headlineMd,
    color: DesignColors.onSurface,
    fontFamily,
    fontWeight: '700',
    fontSize: 17,
  },
  content: { padding: DesignSpacing.md, gap: DesignSpacing.md, paddingBottom: 40 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: DesignSpacing.md },
  errorText: { ...DesignTypography.bodyMd, color: DesignColors.error, fontFamily },

  estateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.md,
    backgroundColor: DesignColors.glassSoft,
    borderRadius: DesignRadius.xl,
    borderWidth: 1,
    borderColor: DesignColors.glassBorder,
    padding: DesignSpacing.md,
  },
  estateImage: { width: 56, height: 56, borderRadius: DesignRadius.md },
  estateImagePlaceholder: {
    width: 56,
    height: 56,
    borderRadius: DesignRadius.md,
    backgroundColor: DesignColors.primaryTint,
    borderWidth: 1,
    borderColor: DesignColors.primaryTintBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  estateInfo: { flex: 1, gap: 2 },
  estateName: { ...DesignTypography.bodyLg, color: DesignColors.onSurface, fontWeight: '700', fontFamily },
  estateMeta: { ...DesignTypography.labelSm, color: DesignColors.onSurfaceVariant, fontFamily },

  bannerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.sm,
    backgroundColor: DesignColors.glassSoft,
    borderRadius: DesignRadius.xl,
    borderWidth: 1,
    borderColor: DesignColors.glassBorder,
    padding: DesignSpacing.md,
  },
  bannerIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: DesignColors.glassFill,
    borderWidth: 1,
    borderColor: DesignColors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerInfo: { flex: 1, gap: 2 },
  bannerTitle: { ...DesignTypography.bodyMd, color: DesignColors.onSurface, fontWeight: '700', fontFamily, fontSize: 13 },
  bannerDesc: { ...DesignTypography.labelSm, color: DesignColors.onSurfaceVariant, fontFamily, lineHeight: 15 },
  bannerAction: {
    backgroundColor: DesignColors.primaryContainer,
    paddingHorizontal: DesignSpacing.md,
    paddingVertical: 8,
    borderRadius: DesignRadius.full,
  },
  bannerActionText: { ...DesignTypography.bodyMd, color: DesignColors.onPrimaryContainer, fontWeight: '700', fontFamily, fontSize: 13 },
  bannerExpired: { borderColor: DesignColors.error, backgroundColor: DesignColors.errorContainer },
  bannerExpiredIcon: { backgroundColor: DesignColors.errorContainer },
  bannerExpiredTitle: { color: DesignColors.error },
  bannerExpiredAction: { backgroundColor: DesignColors.error },
  bannerExpiredActionText: { color: DesignColors.onError, fontWeight: '700', fontSize: 13, fontFamily },
  bannerSuccess: { borderColor: DesignColors.secondary, backgroundColor: DesignColors.successContainer },
  bannerSuccessIcon: { backgroundColor: DesignColors.successContainer },
  bannerSuccessTitle: { color: DesignColors.secondary },

  heroCard: {
    backgroundColor: DesignColors.glassStrong,
    borderRadius: DesignRadius.xl,
    borderWidth: 1,
    borderColor: DesignColors.primaryTintBorder,
    padding: DesignSpacing.lg,
    alignItems: 'center',
    gap: DesignSpacing.sm,
  },
  heroIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: DesignColors.primaryTintStrong,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: DesignColors.primaryBright,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  heroTitle: {
    ...DesignTypography.bodyLg,
    color: DesignColors.onSurface,
    fontWeight: '800',
    fontFamily,
    textAlign: 'center',
  },
  heroDesc: {
    ...DesignTypography.labelSm,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    textAlign: 'center',
    lineHeight: 16,
  },
  heroRoomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.xs,
    marginTop: DesignSpacing.xs,
  },
  heroRoomText: {
    ...DesignTypography.headlineMd,
    color: DesignColors.primaryBright,
    fontFamily,
    fontWeight: '800',
  },

  roomCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.md,
    backgroundColor: DesignColors.glassSoft,
    borderRadius: DesignRadius.xl,
    borderWidth: 1,
    borderColor: DesignColors.glassBorder,
    padding: DesignSpacing.md,
  },
  roomInfo: { flex: 1, gap: 2 },
  roomLabel: { ...DesignTypography.labelCaps, color: DesignColors.onSurfaceVariant, fontFamily, letterSpacing: 1.2 },
  roomValue: { ...DesignTypography.headlineMd, color: DesignColors.onSurface, fontFamily, fontWeight: '800' },
});
