import { StyleSheet } from 'react-native';

import { DesignColors, DesignRadius, fontFamily } from '@/constants/design';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: DesignColors.scrim,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: DesignColors.borderMedium,
    overflow: 'hidden',
  },
  sheetBody: { flex: 1 },
  handleArea: {
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.surfaceContainerHighest,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 14,
  },
  headerSide: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepWrap: {
    flex: 1,
    alignItems: 'center',
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2.4,
    color: DesignColors.primaryBright,
    fontFamily,
    textTransform: 'uppercase',
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: DesignColors.cardBorder,
  },
  scroll: { flex: 1 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    gap: 14,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: -0.2,
    color: DesignColors.onSurface,
    fontFamily,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.2,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    marginTop: -8,
  },
  bold: {
    fontWeight: '700',
    color: DesignColors.onSurface,
  },
  optionList: { gap: 10 },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: DesignColors.surfaceContainerLow,
    borderRadius: DesignRadius.md,
    padding: 14,
    borderWidth: 1,
    borderColor: DesignColors.cardBorder,
    overflow: 'hidden',
  },
  optionCardPressed: {
    borderColor: DesignColors.primaryTintBorder,
    backgroundColor: DesignColors.primaryTint,
  },
  optionAccent: {
    width: 3,
    alignSelf: 'stretch',
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.primaryBright,
  },
  optionIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: DesignColors.primaryTint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionCopy: { flex: 1, gap: 2 },
  optionLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    color: DesignColors.primaryBright,
    fontFamily,
    textTransform: 'uppercase',
  },
  optionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: DesignColors.onSurface,
    fontFamily,
  },
  optionDesc: {
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
  },
  feeChip: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.primaryTint,
    borderWidth: 1,
    borderColor: DesignColors.primaryTintBorder,
  },
  feeChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: DesignColors.primaryBright,
    fontFamily,
  },
  locationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: DesignColors.surfaceContainerLow,
    borderRadius: DesignRadius.md,
    padding: 14,
    borderWidth: 1,
    borderColor: DesignColors.cardBorder,
    overflow: 'hidden',
  },
  locationAccent: {
    width: 3,
    alignSelf: 'stretch',
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.primaryBright,
  },
  locationInfo: { flex: 1, gap: 8 },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  locationText: {
    fontSize: 14,
    fontWeight: '600',
    color: DesignColors.onSurface,
    fontFamily,
    flex: 1,
  },
  lockedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  lockedHint: {
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    flex: 1,
  },
  coordsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  coordBox: {
    flex: 1,
    backgroundColor: DesignColors.surfaceContainerLowest,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: DesignColors.cardBorder,
  },
  coordLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  coordValue: {
    fontSize: 16,
    fontWeight: '700',
    color: DesignColors.onSurface,
    fontFamily,
  },
  exteriorNote: {
    fontSize: 12,
    fontStyle: 'italic',
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    alignSelf: 'center',
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: DesignColors.cardBorder,
  },
  footerBtn: {
    height: 54,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  footerBtnText: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.4,
    color: DesignColors.onPrimary,
    fontFamily,
  },
  switchLink: {
    alignSelf: 'center',
    paddingVertical: 6,
  },
  switchLinkText: {
    fontSize: 13,
    fontWeight: '600',
    color: DesignColors.primaryBright,
    fontFamily,
  },
});
