import { StyleSheet } from 'react-native';

import { DesignColors, DesignRadius, fontFamily } from '@/constants/design';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: DesignColors.scrim,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: DesignColors.borderMedium,
    overflow: 'hidden',
  },
  sheetBody: { flex: 1 },
  handleArea: {
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.surfaceContainerHighest,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 14,
  },
  headerSide: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepWrap: {
    flex: 1,
    alignItems: 'center',
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2.4,
    color: DesignColors.primaryBright,
    fontFamily,
    textTransform: 'uppercase',
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: DesignColors.cardBorder,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
    gap: 14,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: -0.2,
    color: DesignColors.onSurface,
    fontFamily,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.2,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    marginTop: -8,
  },
  bold: {
    fontWeight: '700',
    color: DesignColors.onSurface,
  },
  feeCard: {
    backgroundColor: DesignColors.primaryTint,
    borderRadius: DesignRadius.md,
    borderWidth: 1,
    borderColor: DesignColors.primaryTintBorder,
    paddingVertical: 18,
    alignItems: 'center',
    gap: 4,
  },
  feeLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.6,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    textTransform: 'uppercase',
  },
  feeAmount: {
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.5,
    color: DesignColors.primaryBright,
    fontFamily,
  },
  guaranteeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  guaranteeText: {
    fontSize: 12,
    fontWeight: '400',
    color: DesignColors.onSurfaceVariant,
    fontFamily,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: DesignColors.cardBorder,
  },
  footerBtn: {
    height: 54,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  buttonDisabled: { opacity: 0.6 },
  footerBtnText: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.4,
    color: DesignColors.onPrimary,
    fontFamily,
  },
});
