import { StyleSheet } from 'react-native';

import { DesignColors, DesignRadius, DesignSpacing, DesignTypography, fontFamily } from '@/constants/design';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: DesignColors.surface },
  handleArea: { height: 32, alignItems: 'center', justifyContent: 'center' },
  handle: { width: 44, height: 5, borderRadius: DesignRadius.full, backgroundColor: DesignColors.outlineVariant },
  content: { padding: DesignSpacing.marginMobile, paddingBottom: DesignSpacing.xl * 2, gap: DesignSpacing.lg },
  eyebrow: { ...DesignTypography.labelCaps, color: DesignColors.primaryBright, fontFamily, textTransform: 'uppercase', letterSpacing: 2 },
  headline: { ...DesignTypography.headlineLg, color: DesignColors.onSurface, fontFamily },
  subtitleRow: { flexDirection: 'row', alignItems: 'center', gap: DesignSpacing.sm, flexWrap: 'wrap' },
  subtitle: { ...DesignTypography.bodyMd, color: DesignColors.onSurfaceVariant, fontFamily, flexShrink: 1 },
  section: { gap: DesignSpacing.sm },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: DesignSpacing.xs },
  sectionAccent: { width: 3, height: 14, borderRadius: 2, backgroundColor: DesignColors.primaryBright },
  sectionLabel: { ...DesignTypography.labelCaps, color: DesignColors.onSurfaceVariant, fontFamily, textTransform: 'uppercase', letterSpacing: 1.6 },
  agentCard: {
    flexDirection: 'row', alignItems: 'center', gap: DesignSpacing.md,
    backgroundColor: DesignColors.glassFill, borderRadius: DesignRadius.xl,
    borderWidth: 1, borderColor: DesignColors.cardBorder, padding: DesignSpacing.md,
  },
  agentAvatar: { width: 48, height: 48, borderRadius: DesignRadius.full },
  agentAvatarFallback: { backgroundColor: DesignColors.primaryTint, alignItems: 'center', justifyContent: 'center' },
  agentAvatarText: { ...DesignTypography.bodyLg, color: DesignColors.primaryBright, fontFamily, fontWeight: '700' },
  agentInfo: { flex: 1, gap: 2 },
  agentLabel: { ...DesignTypography.labelSm, color: DesignColors.onSurfaceVariant, fontFamily, textTransform: 'uppercase', letterSpacing: 0.8 },
  agentName: { ...DesignTypography.bodyLg, color: DesignColors.onSurface, fontFamily, fontWeight: '600' },
  agentBadge: {
    width: 28,
    height: 28,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.primaryTint,
    borderWidth: 1,
    borderColor: DesignColors.primaryTintBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignSpacing.md,
    backgroundColor: DesignColors.primaryTint,
    borderRadius: DesignRadius.xl,
    borderWidth: 1,
    borderColor: DesignColors.primaryTintBorder,
    padding: DesignSpacing.md,
  },
  feeIcon: {
    width: 36,
    height: 36,
    borderRadius: DesignRadius.lg,
    backgroundColor: DesignColors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feeCopy: { flex: 1, gap: 2 },
  feeLabel: { ...DesignTypography.labelCaps, color: DesignColors.primaryBright, fontFamily },
  feeHint: { ...DesignTypography.labelSm, color: DesignColors.onSurfaceVariant, fontFamily },
  feeAmount: { ...DesignTypography.headlineMd, color: DesignColors.primaryBright, fontFamily, fontWeight: '700' },
  confirmButton: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: DesignSpacing.sm,
    backgroundColor: DesignColors.primary, borderRadius: DesignRadius.full, height: 54,
  },
  confirmButtonDisabled: { opacity: 0.5 },
  confirmText: { ...DesignTypography.bodyLg, color: DesignColors.onPrimary, fontFamily, fontWeight: '700' },
});
