import type { Estate, SlotCredit, Pod, PodMember, PhysicalRoom } from '@/types/liquidity';

export const MOCK_ESTATES: Estate[] = [
  {
    id: 'est-101',
    name: 'Gida Prestige Residence (Tier 4)',
    description: 'Luxury 4-bedroom student accommodation with high-speed internet, 24/7 power, and biometric security.',
    campus: 'University of Lagos, Akoka',
    property_tier: 4,
    price_per_annum: 1200000,
    physical_rooms_inventory: 25,
    abstract_slots_available: 84,
    primary_image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    rules: ['Quiet hours after 10 PM', 'No indoor smoking', 'Student ID required'],
    amenities: ['Generator', 'Fenced Gate', 'Internet', 'Wardrobe', 'Borehole Water'],
  },
  {
    id: 'est-102',
    name: 'Gida Scholars Enclave (Tier 3)',
    description: 'Modern 3-slot shared apartment designed for collaborative student living.',
    campus: 'University of Lagos, Akoka',
    property_tier: 3,
    price_per_annum: 900000,
    physical_rooms_inventory: 15,
    abstract_slots_available: 42,
    primary_image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    rules: ['No pets allowed', 'Shared kitchen hygiene rules apply', 'No unauthorized sleepovers'],
    amenities: ['Shared Kitchen', 'Shared Bathroom', 'Generator', 'Cabinets'],
  },
  {
    id: 'est-103',
    name: 'Gida Sovereign Studio (Tier 1)',
    description: 'Private executive studio apartment for solo living with direct auto-minting.',
    campus: 'University of Lagos, Akoka',
    property_tier: 1,
    price_per_annum: 1800000,
    physical_rooms_inventory: 8,
    abstract_slots_available: 8,
    primary_image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    rules: ['Single occupancy only', 'Quiet hours after 11 PM'],
    amenities: ['Generator', 'Fenced Gate', 'Internet', 'Burglary Proof', 'Wardrobe'],
  },
  {
    id: 'est-104',
    name: 'Aura Twin Lofts (Tier 2)',
    description: 'Contemporary 2-bedroom shared suite tailored for harmonious 50/50 matching pods.',
    campus: 'University of Lagos, Akoka',
    property_tier: 2,
    price_per_annum: 12000000,
    physical_rooms_inventory: 15,
    abstract_slots_available: 30,
    primary_image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    rules: ['Quiet hours after 10 PM', 'Equal cleaning duties', 'Student ID required'],
    amenities: ['Generator', 'Fenced Gate', 'Internet', 'Co-Working Lounge'],
  },
  {
    id: 'est-105',
    name: 'Emerald Quintet Suites (Tier 5)',
    description: 'Ultra-luxury 5-bedroom residence enforcing Odd-Tier protection rules.',
    campus: 'University of Lagos, Akoka',
    property_tier: 5,
    price_per_annum: 55000000,
    physical_rooms_inventory: 12,
    abstract_slots_available: 60,
    primary_image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    rules: ['No pets allowed', 'Shared kitchen schedule apply'],
    amenities: ['Waterfront View', 'Olympic Pool', 'Generator', 'Cabinets'],
  },
  {
    id: 'est-106',
    name: 'Royal Hexa Manor (Tier 6)',
    description: 'Grand 6-bedroom communal residence designed for flexible student pods and friend combinations.',
    campus: 'University of Lagos, Akoka',
    property_tier: 6,
    price_per_annum: 65000000,
    physical_rooms_inventory: 10,
    abstract_slots_available: 60,
    primary_image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    rules: ['Collaborative student events allowed with notice', 'Quiet hours after 11 PM'],
    amenities: ['Generator', 'Fenced Gate', 'Internet', 'Game Lounge'],
  },
];

export const MOCK_SLOT_CREDITS: SlotCredit[] = [
  {
    id: 'credit-001',
    user_id: 'usr-901',
    estate_id: 'est-101',
    property_tier: 4,
    intent_size: 2,
    target_occupancy: 4,
    status: 'paid_unmatched',
    invite_code: 'GIDA-POD-4821',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    payment_deadline: new Date(Date.now() + 22 * 3600 * 1000).toISOString(),
    estate: MOCK_ESTATES[0],
  },
];

export const MOCK_LOBBY_PEERS: PodMember[] = [
  {
    user_id: 'peer-201',
    full_name: 'Chinedu Okeke',
    intent_size: 2,
    campus: 'UNILAG (Main Campus)',
    major: 'Computer Science',
    cleanliness_score: 5,
    sleep_schedule: 'Night owl (2 AM)',
    slot_credit_id: 'credit-peer-201',
  },
  {
    user_id: 'peer-202',
    full_name: 'Babajide Adeleke',
    intent_size: 2,
    campus: 'UNILAG (Main Campus)',
    major: 'Electrical Engineering',
    cleanliness_score: 4,
    sleep_schedule: 'Early bird (10 PM)',
    slot_credit_id: 'credit-peer-202',
  },
  {
    user_id: 'peer-203',
    full_name: 'Tobi Alabi',
    intent_size: 1,
    campus: 'UNILAG (Main Campus)',
    major: 'Architecture',
    cleanliness_score: 5,
    sleep_schedule: 'Flexible',
    slot_credit_id: 'credit-peer-203',
  },
];

export const MOCK_PODS: Pod[] = [
  {
    id: 'pod-551',
    estate_id: 'est-101',
    property_tier: 4,
    matched_gender: 'ANY',
    target_occupancy: 4,
    members: [
      {
        user_id: 'usr-901',
        full_name: 'You (Current User)',
        intent_size: 2,
        campus: 'UNILAG (Main Campus)',
        major: 'Law',
        cleanliness_score: 5,
        sleep_schedule: 'Midnight (12 AM)',
        slot_credit_id: 'credit-001',
      },
    ],
    current_total_intent: 2,
    is_finalized: false,
    physical_room_id: null,
    created_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_PHYSICAL_ROOMS: PhysicalRoom[] = [
  {
    id: 'room-701',
    estate_id: 'est-101',
    property_tier: 4,
    physical_door_number: 'Apt 4B - Prestige Wing',
    gender_lock: 'NONE',
    assigned_pod_id: 'pod-551',
    latecomer_slots_available: 0,
  },
];
