import { type RoommateProfile } from '@/types/roommates';

export const roommateProfiles: RoommateProfile[] = [
  {
    id: 'alex-rivera',
    name: 'Alex Rivera',
    age: 24,
    avatar: require('@/dummy/images/people/Alex.png'),
    university: 'FUTMinna',
    department: 'Cyber Security',
    level: '300L',
    compatibility: 94,
    moveInDate: 'Sept 1',
    budget: '₦120k/mo',
    bio: 'Looking for a quiet place near Gidan Kwano. I cook a lot and respect quiet hours on weekdays.',
    chips: [
      { label: 'Clean', value: 'High' },
      { label: 'Party', value: 'Low' },
      { label: 'Pets', value: 'Ok' },
      { label: 'Student', value: 'Yes' },
    ],
  },
  {
    id: 'zainab-abdullah',
    name: 'Zainab Abdullah',
    age: 22,
    avatar: require('@/dummy/images/people/Zainab Abdullah.png'),
    university: 'FUTMinna',
    department: 'Civil Engineering',
    level: '200L',
    compatibility: 87,
    moveInDate: 'Now',
    budget: '₦80k/mo',
    bio: 'Need a female roommate near Bosso campus gate. I prefer a clean and organized space.',
    chips: [
      { label: 'Clean', value: 'Very High' },
      { label: 'Party', value: 'Never' },
      { label: 'Pets', value: 'No' },
      { label: 'Student', value: 'Yes' },
    ],
  },
  {
    id: 'chidi-okonkwo',
    name: 'Chidi Okonkwo',
    age: 23,
    avatar: require('@/dummy/images/people/Chidi.png'),
    university: 'FUTMinna',
    department: 'Mechanical Engineering',
    level: '300L',
    compatibility: 82,
    moveInDate: 'Oct 1',
    budget: '₦100k/mo',
    bio: 'Gym enthusiast looking for an active roommate who values fitness and discipline.',
    chips: [
      { label: 'Clean', value: 'High' },
      { label: 'Party', value: 'Sometimes' },
      { label: 'Pets', value: 'Ok' },
      { label: 'Student', value: 'Yes' },
    ],
  },
  {
    id: 'amina-mohammed',
    name: 'Amina Mohammed',
    age: 21,
    avatar: require('@/dummy/images/people/Amina.png'),
    university: 'FUTMinna',
    department: 'Computer Science',
    level: '200L',
    compatibility: 79,
    moveInDate: 'Sept 15',
    budget: '₦90k/mo',
    bio: 'Studying late nights. Looking for someone who does not mind a quiet study partner.',
    chips: [
      { label: 'Clean', value: 'Medium' },
      { label: 'Party', value: 'Never' },
      { label: 'Pets', value: 'No' },
      { label: 'Student', value: 'Yes' },
    ],
  },
  {
    id: 'daniel-otu',
    name: 'Daniel Otu',
    age: 25,
    avatar: require('@/dummy/images/people/Daniel.png'),
    university: 'FUTMinna',
    department: 'Architecture',
    level: '400L',
    compatibility: 91,
    moveInDate: 'Now',
    budget: '₦150k/mo',
    bio: 'Final year architecture student. I have a car so proximity to parking is a plus.',
    chips: [
      { label: 'Clean', value: 'High' },
      { label: 'Party', value: 'Low' },
      { label: 'Pets', value: 'Ok' },
      { label: 'Student', value: 'Yes' },
    ],
  },
  {
    id: 'fatima-ibrahim',
    name: 'Fatima Ibrahim',
    age: 22,
    avatar: require('@/dummy/images/people/Fatima.png'),
    university: 'FUTMinna',
    department: 'Biochemistry',
    level: '300L',
    compatibility: 76,
    moveInDate: 'Dec 1',
    budget: '₦70k/mo',
    bio: 'Looking for a female-only apartment near campus. I keep to myself mostly.',
    chips: [
      { label: 'Clean', value: 'High' },
      { label: 'Party', value: 'Never' },
      { label: 'Pets', value: 'No' },
      { label: 'Student', value: 'Yes' },
    ],
  },
];
