import { StyleSheet } from 'react-native';

import { DesignColors, DesignRadius, fontFamily } from '@/constants/design';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  backdrop: {
    flex: 1,
    backgroundColor: DesignColors.scrim,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: DesignColors.surfaceContainerLowest,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: DesignColors.borderMedium,
    overflow: 'hidden',
  },
  scrimSpace: { flex: 1 },
  handleArea: {
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.surfaceContainerHighest,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 14,
  },
  headerSide: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepWrap: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2.4,
    color: DesignColors.primaryBright,
    fontFamily,
    textTransform: 'uppercase',
  },
  progressTrack: {
    flexDirection: 'row',
    gap: 5,
    width: 64,
  },
  progressSegment: {
    flex: 1,
    height: 3,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.surfaceContainerHighest,
  },
  progressSegmentActive: {
    backgroundColor: DesignColors.primaryBright,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: DesignColors.cardBorder,
  },
  scroll: { flex: 1 },
  stepContent: { gap: 14 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    gap: 14,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: -0.2,
    color: DesignColors.onSurface,
    fontFamily,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: 0.2,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
    marginTop: -8,
  },
  center: { flex: 1, alignSelf: 'center', marginVertical: 24 },
  errorText: {
    fontSize: 13,
    color: DesignColors.error,
    textAlign: 'center',
    marginVertical: 24,
    fontFamily,
  },
  listingMini: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: DesignColors.surfaceContainerLow,
    borderRadius: DesignRadius.md,
    padding: 10,
    borderWidth: 1,
    borderColor: DesignColors.cardBorder,
    overflow: 'hidden',
  },
  listingAccent: {
    width: 3,
    alignSelf: 'stretch',
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.primaryBright,
  },
  listingThumb: { width: 44, height: 44, borderRadius: 10 },
  listingMiniInfo: { flex: 1, gap: 2 },
  listingMiniTitle: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.1,
    color: DesignColors.onSurface,
    fontFamily,
  },
  listingMiniPrice: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.1,
    color: DesignColors.primaryBright,
    fontFamily,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: DesignColors.cardBorder,
  },
  footerBtn: {
    height: 54,
    borderRadius: DesignRadius.full,
    backgroundColor: DesignColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBtnDisabled: { opacity: 0.5 },
  footerBtnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  footerBtnText: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.4,
    color: DesignColors.onPrimary,
    fontFamily,
  },
  orRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 2,
  },
  orLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: DesignColors.borderMedium,
  },
  orText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
  },
  invitedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DesignRadius.md,
    backgroundColor: DesignColors.primaryTint,
    borderRadius: DesignRadius.md,
    borderWidth: 1,
    borderColor: DesignColors.primaryTintBorder,
    borderStyle: 'dashed',
    paddingVertical: DesignRadius.md,
    paddingHorizontal: DesignRadius.md,
  },
  invitedIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: DesignColors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  invitedCopy: { flex: 1, gap: 2, paddingRight: 4 },
  invitedTitle: {
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.2,
    color: DesignColors.onPrimaryContainer,
    fontFamily,
  },
  invitedDesc: {
    fontSize: 12,
    lineHeight: 16,
    color: DesignColors.onSurfaceVariant,
    fontFamily,
  },
});
